version: '3'

services:
  follow:
    container_name: "follow-api"
    depends_on:
      - follow_db
    build:
      context: .
      dockerfile: ./jj-follower-service/Dockerfile
    ports:
      - 8081:8080
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${FOLLOW_DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${FOLLOW_DB_PORT}
    networks:
      - keycloak-net

  follow_db:
    container_name: follow_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${FOLLOW_POSTGRES_DB}
    volumes:
      - followdata:/var/lib/postgresql/data

  post:
    container_name: "post-api"
    depends_on:
      - post_db
    build:
      context: .
      dockerfile: ./jj-post-service/Dockerfile
    ports:
      - 8082:8080
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${POST_DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${POST_DB_PORT}
    networks:
      - keycloak-net

  post_db:
    container_name: post_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POST_POSTGRES_DB}
    volumes:
      - postdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    depends_on:
      - keycloak_db
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth
      PROXY_ADDRESS_FORWARDING: "true"
      KC_PROXY: passthrough
      KEYCLOAK_PROXY: passthrough
    command: start-dev
    networks:
      - keycloak-net

  keycloak_db:
    container_name: keycloak_db
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
    volumes:
      - keycloakdata:/var/lib/postgresql/data
  
  reverse-proxy:
    container_name: "reverse-proxy"
    image: nginx
    ports:
      - 8084:80
    volumes:
      - ./nginx/build/:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - keycloak-net

volumes:
  followdata:
    external: true
  postdata:
    external: true
  keycloakdata:
    external: true

networks:
  keycloak-net:
