version: '3'

services:
  follow-api:
    container_name: "follow-api"
    depends_on:
      - follow_db
    image: ghcr.io/tombtomb/jj-follower-service:main
    ports:
      - 8081:8080
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${FOLLOW_DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${FOLLOW_DB_PORT}
      DD_API_KEY: ${DD_API_KEY}
    networks:
      - keycloak-net
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "follow-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'


  follow_db:
    container_name: follow_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${FOLLOW_POSTGRES_DB}
      DD_API_KEY: ${DD_API_KEY}
    volumes:
      - followdata:/var/lib/postgresql/data

  post-api:
    container_name: "post-api"
    depends_on:
      - post_db
    image: ghcr.io/tombtomb/jj-post-service:main
    ports:
      - 8082:8080
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${POST_DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${POST_DB_PORT}
      DD_API_KEY: ${DD_API_KEY}
    networks:
      - keycloak-net
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "post-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'


  post_db:
    container_name: post_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POST_POSTGRES_DB}
    volumes:
      - postdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    depends_on:
      - keycloak_db
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth
      PROXY_ADDRESS_FORWARDING: "true"
      KC_PROXY: passthrough
      KEYCLOAK_PROXY: passthrough
    command: start-dev
    networks:
      - keycloak-net

  keycloak_db:
    container_name: keycloak_db
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
    volumes:
      - keycloakdata:/var/lib/postgresql/data
  
  reverse-proxy:
    container_name: "reverse-proxy"
    image: ghcr.io/tombtomb/jj-frontend:develop
    ports:
      - 80:80
      - 433:433
    environment:
      DD_API_KEY: ${DD_API_KEY}
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
    networks:
      - keycloak-net
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "reverse-proxy", "log_processing_rules": [{"type": "mask_sequences", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw

  datadog:
    image: datadog/agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

volumes:
  followdata:
    external: true
  postdata:
    external: true
  keycloakdata:
    external: true

networks:
  keycloak-net:
